name: hetu_binding_generator
description: A binding-code generator for Hetu script language. You can generate glue codes from Flutter/Dart library, your own codes, or any packages. Then you can use them in the Hetu script.
version: 1.0.17
homepage: https://github.com/hetu-script/hetu-script-autobinding

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^4.7.0
  args: ^2.3.0
  json_annotation: ^4.3.0
  mustache_template: ^2.0.0
  hetu_script: ^0.4.2+1
  hetu_script_dev_tools: ^0.1.0+2

dev_dependencies:
  json_serializable: ^6.0.1
  lints: ^2.0.0
  test: ^1.19.4
